version: "3"
services:
  nginx_proxy:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    depends_on:
      - db_nginx
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./_hsts.conf:/app/templates/_hsts.conf:ro
    restart: always
    networks:
        - app-network

  db_nginx:
    image: 'yobasystems/alpine-mariadb:latest'
    container_name: db_nginx
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    networks:
        - app-network

  precios_locos_web:
    image: precios_locos_web
    container_name: precios_locos_web
    build:
      context: ./precios_locos_web
    volumes:
      - ./precios_locos_web:/usr/share/nginx/html:ro
    depends_on:
      - nginx_proxy
      - db_nginx
    expose:
      - "8000"
    restart: always
    networks:
        - app-network

  x_api:
    image: x_api
    container_name: x_api
    build:
      context: ./x_api
    volumes:
      - ./x_api:/usr/share/nginx/html:ro
    depends_on:
      - nginx_proxy
      - db_nginx
      - precios_locos_web
    expose:
      - "8001"
    restart: always
    networks:
        - app-network

networks:
   app-network:
      driver: bridge